var word = require("./word.js");
var inquirer = require("inquirer");

var letterArray = "abcdefghijklmnopqrstuvwxyz";

var SpaceProjects = [
    "mercury",
    "gemini",
    "apollo",
    "saturn",
    "skylab",
    "iss",
    "sputnik",
    "kepler",
    "discovery",
    "pioneer",
    "luna",
    "titan",
    "vostok",
    "soyuz",
    "surveyor",
    "curiosity",
    "voyager",
    "mariner",
    "spirit",
    "opportunity",
    "viking",
    "juno",
    "stardust",
    "genesis",
    "columbia",
    "shenzon",
    "pioneer",
    "venus",
    "mars",
    "earth",
    "pluto",
    "neptune",
    "uranus",
    "saturn",
    "jupiter",
    "europa",
    "rhea",
    "callisto",
    "hyperion",
];